### ISSUE TITLE
[v7] Execution failed for task ':react-native-navigation:compileReactNative60DebugKotlin'

### ISSUE THREAD

**Issue by tarouboy** [wix/react-native-navigation#6758]
## 🐛 Bug Report

It was fine when I was compiling RNN v7.0, after upgrading to v7.2 or v7.3, when I compile will show below error:
**Execution failed for task ':react-native-navigation:compileReactNative60DebugKotlin'**

I can reproduce by creating a new test app and followed the instruction here:
https://wix.github.io/react-native-navigation/docs/installing

I've tried updating the build.gradle setting with RNNKotlinVersion = "1.3.72" and com.android.tools.build:gradle = 3.6.1 ( ref: https://github.com/wix/react-native-navigation/issues/5987 ) or by following the playground app, both not working.

With the same build.gradle and all the setup, if I downgrade to v7.0 then it runs fine.
Thanks!

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing)?

Yes

## To Reproduce

(Write your steps here:)

1. react-native init newproject 
2. npm i react-native-navigation@7.3.0
3. npx rnn-link
4. update index.js
5. react-native run-android

## Expected behavior

App start

## Actual Behavior

Execution failed for task ':react-native-navigation:compileReactNative60DebugKotlin'

## Your Environment

- React Native Navigation version: 7.3.0
- React Native version: 0.61.5
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Both, Android 7-10

## Reproducible Demo

N/A

**Comment by tarouboy** [comment]
After upgrading Android Studio to 4.1, I am able to get the error from the log.

/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/options/parsers/TypefaceLoader.kt: (6, 38): 
Unresolved reference: ReactTypefaceUtils

Can someone help pls?

**Comment by danilobuerger** [comment]
Looking at the react native changelog it seems that `ReactTypefaceUtils` only became available starting in 0.62. 
@guyca Any way we can make this backward compatible?

**Comment by guyca** [comment]
@danilobuerger Looking at [ReactTypefaceUtils.java](https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/views/text/ReactTypefaceUtils.java) it has no dependencies on classes from React Native.

We can safely copy it to RNN's utils folder and use our copy. We've already spoken about setting min required RN version to 0.63 in the next major version for better Color typings in `Options.ts`. We can add another task to v8 to delete the file and require it from RN.

**Comment by danilobuerger** [comment]
@tarouboy can you please try out #6778 and see if it fixes your issue and you are able to use rn 0.61 with it?

**Comment by tarouboy** [comment]
> @tarouboy can you please try out #6778 and see if it fixes your issue and you are able to use rn 0.61 with it?

Unfortunately, installed 7.4.0 and still not able to compile.

...node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/ReactGateway.java:47: error: cannot find symbol
            host.getReactInstanceManager().onConfigurationChanged(activity, newConfig);

symbol:   method onConfigurationChanged(NavigationActivity,Configuration)
location: class ReactInstanceManager

**Comment by danilobuerger** [comment]
@tarouboy Does it work now with 7.5.0?

**Comment by tarouboy** [comment]
> @tarouboy Does it work now with 7.5.0?

Sorry that I missed the question. 
Yes, 7.5.0+ is working fine.

**Comment by Irenedan** [comment]
@danilobuerger @tarouboy  Hello, Could you please tell me the version of your used react-native and react-native-navigation? I have the same issue.

**Comment by nathantqn** [comment]
Hi @tarouboy, I have same question as @Irenedan, I'm still getting that error in my app, and my react native version is like you 0.61.5, I upgraded to the latest lib of react-native-navigation but the issue remains

**Comment by tarouboy** [comment]
> Hi @tarouboy, I have same question as @Irenedan, I'm still getting that error in my app, and my react native version is like you 0.61.5, I upgraded to the latest lib of react-native-navigation but the issue remains

We have upgraded the RN to the latest version already.
