### PR TITLE
[v2] add support for react-native 0.57.0

### PR DESCRIPTION
**Pull request by abdullah-sr**

### CODE REVIEW

**Comment by esipavicius** [comment]
So what I need to do to run react-native-navigation v2 with react-native 57? I geting:

error: cannot find symbol
import com.facebook.react.uimanager.UIImplementationProvider;
...

or if add "|| names.contains("reactNative56")"
does not exist
import com.reactnativenavigation.NavigationActivity;
....

I need to wait for release?

**Comment by holparb** [comment]
Can someone who feels confident in the topic please review the PR and accept if it's okay?
We would love to have RNN with RN 0.57 support.  :)

**Comment by DVSoftware** [comment]
Doesn't work with latest:

```
/Users/dvsoftware/Projects/-/node_modules/react-native-navigation/lib/android/app/src/reactNative57/java/com/reactnativenavigation/react/NavigationReactNativeHost.java:24: error: duplicate class: com.reactnativenavigation.react.NavigationReactNativeHost
public class NavigationReactNativeHost extends ReactNativeHost implements BundleDownloadListenerProvider {
       ^
/Users/dvsoftware/Projects/-/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactNativeHost.java:86: error: cannot find symbol
                .setUIImplementationProvider(getUIImplementationProvider())
                                             ^
  symbol:   method getUIImplementationProvider()
  location: class NavigationReactNativeHost
```

**Comment by LeVadim** [comment]
Any update on this? Looking forward to it.
 Thank you

**Comment by leonardoballand** [comment]
I've created a repository that is working, while the PR is waiting to be merged.

https://github.com/leonardoballand/react-native-navigation-rn57

**Comment by abdullah-sr** [comment]
@esipavicius @DVSoftware this hasn't been merged so you can't use it just yet. We're waiting on someone to review this and accept it. @guyca would you please review this so these beautiful people can use navigation with the new react 0.57?

**Comment by ammichael** [comment]
@guyca sorry bother (once more), but with iOS 12 release, RN 0.57 is almost mandatory since it fixes tons of XCode 10 problems. Could you please review and merge this PR?

Thanks a lot!

**Comment by DVSoftware** [comment]
> @esipavicius @DVSoftware this hasn't been merged so you can't use it just yet. We're waiting on someone to review this and accept it. @guyca would you please review this so these beautiful people can use navigation with the new react 0.57?

I know, i applied the patch, but i'm getting the mentioned errors

**Comment by epileftro85** [comment]
is this available now?

**Comment by urosappdev** [comment]
Would be great if this gets merged.

**Comment by esipavicius** [comment]
> Would be great if this gets merged

But it has red light. Everywhere is red ;D

**Comment by urosappdev** [comment]
Works on fresh 0.57 i don’t know why is it failing.

**Comment by epileftro85** [comment]
On Android it can build app because reactNative57 is not present

**Comment by ujwal-setlur** [comment]
I applied the patch to my project. Does not work:

```
> Task :react-native-navigation:compileReactNative57DebugJavaWithJavac FAILED
/Users/ujwal/Work/seamlz/seamlz-mobile/node_modules/react-native-navigation/lib/android/app/src/reactNative57/java/com/reactnativenavigation/react/NavigationReactNativeHost.java:24: error: duplicate class: com.reactnativenavigation.react.NavigationReactNativeHost
public class NavigationReactNativeHost extends ReactNativeHost implements BundleDownloadListenerProvider {
       ^
/Users/ujwal/Work/seamlz/seamlz-mobile/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactNativeHost.java:86: error: cannot find symbol
                .setUIImplementationProvider(getUIImplementationProvider())
                                             ^
  symbol:   method getUIImplementationProvider()
  location: class NavigationReactNativeHost
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
```

**Comment by ammichael** [comment]
@ujwal-setlur did you remember to filter the RN56 variant on build.gradle?

**Comment by ujwal-setlur** [comment]
@ammichael  filter? How? Here is my build.gradle:

```
    defaultConfig {
        applicationId "com.seamlz.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57"
        versionCode buildNumber
        versionName "${versionMajor}.${versionMinor}.${versionPatch}"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
```

**Comment by ujwal-setlur** [comment]
Essentially, I am running into the same issue as @DVSoftware

**Comment by ammichael** [comment]
@ujwal-setlur try adding this to your /android/build.gradle:

```
subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin("android") || subproject.plugins.hasPlugin("android-library"))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
                // Ignoring RN Navigation Flavors. Needs to be updated when lib is updated
                variantFilter { variant ->
                  def names = variant.flavors*.name
                  if (names.contains("reactNative51") || names.contains("reactNative55") || names.contains("reactNative56")) {
                      setIgnore(true)
                  }
                }
            }
        }
    }
}
```

**Comment by ujwal-setlur** [comment]
@ammichael unfortunately, I still get that error...

It seems not so much of a conflict between reactNative57 and reactNative56, but more between reactNative57 and the code under src/main/java/com/reactnativenavigation/react/NavigationReactNativeHost.java

They both declare NavigationReactNativeHost class

**Comment by mcousillas6** [comment]
Hi guys, Any news about this?

**Comment by ammichael** [comment]
This has been opened more than 1 month ago. I'm in a really bad situation here; can't update to RN 0.57 and release my iOS 12 update while this isn't merged. It's very likely there are more people in the same situation. Please, can somebody (@guyca) take over this merge, fix what is failing and finally merge it?!

Please?

**Comment by ujwal-setlur** [comment]
Yes me too please. Frankly, I am contemplating moving off RNN. Issues with RN releases, issues with code push. I really like this library, but it's getting hard...

**Comment by DVSoftware** [comment]
> Yes me too please. Frankly, I am contemplating moving off RNN. Issues with RN releases, issues with code push. I really like this library, but it's getting hard...

We pulled the plug and moved to react-navigation. It was worth the effort, most bugs we had was due to RNN. We now removed tons of hacks for delaying keyboard appearing and similar...

**Comment by hugows** [comment]
> > Yes me too please. Frankly, I am contemplating moving off RNN. Issues with RN releases, issues with code push. I really like this library, but it's getting hard...
> 
> We pulled the plug and moved to react-navigation. It was worth the effort, most bugs we had was due to RNN. We now removed tons of hacks for delaying keyboard appearing and similar...

How is the performance? Everyone always said that RNN was much better than react-navigation regarding performance and bugs and everything...

**Comment by DVSoftware** [comment]
> How is the performance? Everyone always said that RNN was much better than react-navigation regarding performance and bugs and everything...

Honestly, so far, it seems that performance is better, also less visual glitches, screen flashes, etc.

**Comment by ujwal-setlur** [comment]
@DVSoftware thanks. Well, I know what I am doing today...

**Comment by esipavicius** [comment]
> > How is the performance? Everyone always said that RNN was much better than react-navigation regarding performance and bugs and everything...
> 
> Honestly, so far, it seems that performance is better, also less visual glitches, screen flashes, etc.

I Moved from react-navigation for package implementation. i have some of packages with small documentation. Its easy to register screen and you ready to use it. This is harder with react-navigation.

About performance - yes react-native works smoother, no glitches, no screen flashes comparing with react-native-navigation. But right now I think its not big problem.

I like react-native-navigation it is not needed to init navigation component first time rendering app. It just register all components and you can access it from everywhere. 

But react-native-navigation has big init root screen configuration tree.

**Comment by abdullah-sr** [comment]
For the people who are in need of this, you guys can `npm install https://github.com/abdullah-sr/react-native-navigation#build`. I try to keep it up to date with the v2 branch. It's what we're using and it's working for us.

**Comment by anilgurindapalli** [comment]
@abdullah-sr i have installed the packages from the above link.. But still issue didn't get solved.
"app:transformDexArchiveWithExternalLibsDexMergerForReactNative57Debug" facing this issue

**Comment by stokesbga** [comment]
@abdullah-sr i love you! thank you so much for the help!

**Comment by stokesbga** [comment]
> @abdullah-sr i have installed the packages from the above link.. But still issue didn't get solved.
> "app:transformDexArchiveWithExternalLibsDexMergerForReactNative57Debug" facing this issue

```multiDexEnabled true```

**Comment by abdullah-sr** [comment]
> @abdullah-sr i have installed the packages from the above link.. But still issue didn't get solved.
> "app:transformDexArchiveWithExternalLibsDexMergerForReactNative57Debug" facing this issue

try running `./gradlew clean` under the Android directory and see if that helps

**Comment by abdullah-sr** [comment]
> @abdullah-sr i love you! thank you so much for the help!

glad i could help :)

**Comment by guruparan** [comment]
Any idea when this will be merged officially ?

**Comment by nightgrey** [comment]
> @abdullah-sr i have installed the packages from the above link.. But still issue didn't get solved.
> "app:transformDexArchiveWithExternalLibsDexMergerForReactNative57Debug" facing this issue

I have a similiar issue. I installed ``https://github.com/abdullah-sr/react-native-navigation#build`` and got an issue similar to his. I read all the messages here and tried some things, but ultimately, I'm a noob when it comes to the android development environment.

Could someone check out the exception and the configuration I have and point me in the right direction OR, alternatively, point me to a newly initiated react-native 0.57.1 + react-native-navigation@alpha project with working android implementation?

**Exception when running run-android**
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```
**android/build.gradle**
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "27.0.3"
        minSdkVersion = 19
        compileSdkVersion = 26
        targetSdkVersion = 26
        supportLibVersion = "26.1.0"
    }
    repositories {
        google()
        mavenLocal()
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
        maven { url 'https://jitpack.io' }
    }
}

subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin("android") || subproject.plugins.hasPlugin("android-library"))) {
            android {
                compileSdkVersion rootProject.ext.compileSdkVersion
                buildToolsVersion rootProject.ext.buildToolsVersion
                // Ignoring RN Navigation Flavors. Needs to be updated when lib is updated
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (names.contains("reactNative51") || names.contains("reactNative55") || names.contains("reactNative56")) {
                        setIgnore(true)
                    }
                }
            }
        }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}
```

**android/gradle.properties**
```
# Project-wide Gradle settings.

# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx10248m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true

# Disable incremental resource processing as it broke release build
android.enableAapt2=false
```

***android/settings.gradle***
```
rootProject.name = 'reactnative'

include ':react-native-navigation'
project(':react-native-navigation').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-navigation/lib/android/app/')

include ':app'
```

**android/src/build.gradle**
```
apply plugin: "com.android.application"

import com.android.build.OutputFile

/**
 * The react.gradle file registers a task for each build variant (e.g. bundleDebugJsAndAssets
 * and bundleReleaseJsAndAssets).
 * These basically call `react-native bundle` with the correct arguments during the Android build
 * cycle. By default, bundleDebugJsAndAssets is skipped, as in debug/dev mode we prefer to load the
 * bundle directly from the development server. Below you can see all the possible configurations
 * and their defaults. If you decide to add a configuration block, make sure to add it before the
 * `apply from: "../../node_modules/react-native/react.gradle"` line.
 *
 * project.ext.react = [
 *   // the name of the generated asset file containing your JS bundle
 *   bundleAssetName: "index.android.bundle",
 *
 *   // the entry file for bundle generation
 *   entryFile: "index.android.js",
 *
 *   // whether to bundle JS and assets in debug mode
 *   bundleInDebug: false,
 *
 *   // whether to bundle JS and assets in release mode
 *   bundleInRelease: true,
 *
 *   // whether to bundle JS and assets in another build variant (if configured).
 *   // See http://tools.android.com/tech-docs/new-build-system/user-guide#TOC-Build-Variants
 *   // The configuration property can be in the following formats
 *   //         'bundleIn${productFlavor}${buildType}'
 *   //         'bundleIn${buildType}'
 *   // bundleInFreeDebug: true,
 *   // bundleInPaidRelease: true,
 *   // bundleInBeta: true,
 *
 *   // whether to disable dev mode in custom build variants (by default only disabled in release)
 *   // for example: to disable dev mode in the staging build type (if configured)
 *   devDisabledInStaging: true,
 *   // The configuration property can be in the following formats
 *   //         'devDisabledIn${productFlavor}${buildType}'
 *   //         'devDisabledIn${buildType}'
 *
 *   // the root of your project, i.e. where "package.json" lives
 *   root: "../../",
 *
 *   // where to put the JS bundle asset in debug mode
 *   jsBundleDirDebug: "$buildDir/intermediates/assets/debug",
 *
 *   // where to put the JS bundle asset in release mode
 *   jsBundleDirRelease: "$buildDir/intermediates/assets/release",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in debug mode
 *   resourcesDirDebug: "$buildDir/intermediates/res/merged/debug",
 *
 *   // where to put drawable resources / React Native assets, e.g. the ones you use via
 *   // require('./image.png')), in release mode
 *   resourcesDirRelease: "$buildDir/intermediates/res/merged/release",
 *
 *   // by default the gradle tasks are skipped if none of the JS files or assets change; this means
 *   // that we don't look at files in android/ or ios/ to determine whether the tasks are up to
 *   // date; if you have any other folders that you want to ignore for performance reasons (gradle
 *   // indexes the entire tree), add them here. Alternatively, if you have JS files in android/
 *   // for example, you might want to remove it from here.
 *   inputExcludes: ["android/**", "ios/**"],
 *
 *   // override which node gets called and with what additional arguments
 *   nodeExecutableAndArgs: ["node"],
 *
 *   // supply additional arguments to the packager
 *   extraPackagerArgs: []
 * ]
 */

project.ext.react = [
    entryFile: "index.js"
]

apply from: "../../node_modules/react-native/react.gradle"

/**
 * Set this to true to create two separate APKs instead of one:
 *   - An APK that only works on ARM devices
 *   - An APK that only works on x86 devices
 * The advantage is the size of the APK is reduced by about 4MB.
 * Upload all the APKs to the Play Store and people will download
 * the correct one based on the CPU architecture of their device.
 */
def enableSeparateBuildPerCPUArchitecture = false

/**
 * Run Proguard to shrink the Java bytecode in release builds.
 */
def enableProguardInReleaseBuilds = false

android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion rootProject.ext.buildToolsVersion

    defaultConfig {
        applicationId "com.reactnative"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57"
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-navigation')
}

// Run this once to be able to run the application with BUCK
// puts all compile dependencies into folder libs for BUCK to use
task copyDownloadableDepsToLibs(type: Copy) {
    from configurations.compile
    into 'libs'
}
```

**android/src/main/java/com/reactnative/MainActivity.java**
```
package com.reactnative;

import com.facebook.react.ReactActivity;
import com.reactnativenavigation.NavigationActivity;

public class MainActivity extends NavigationActivity {
}
```

**android/src/main/java/com/reactnative/MainApplication.java**
```
package com.reactnative;

import android.app.Application;

import com.facebook.react.ReactApplication;
import com.facebook.react.ReactNativeHost;
import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;
import com.facebook.soloader.SoLoader;

import com.reactnativenavigation.NavigationApplication;
import com.reactnativenavigation.react.NavigationReactNativeHost;
import com.reactnativenavigation.react.ReactGateway;

import java.util.Arrays;
import java.util.List;

public class MainApplication extends NavigationApplication {

  @Override
  protected ReactGateway createReactGateway() {
    ReactNativeHost host = new NavigationReactNativeHost(this, isDebug(), createAdditionalReactPackages()) {
      @Override
      protected String getJSMainModuleName() {
        return "index";
      }
    };
    return new ReactGateway(this, isDebug(), host);
  }

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  protected List<ReactPackage> getPackages() {
    // Add additional packages you require here
    // No need to add RnnPackage and MainReactPackage
    return Arrays.<ReactPackage>asList(
            // eg. new VectorIconsPackage()
    );
  }

  @Override
  public List<ReactPackage> createAdditionalReactPackages() {
    return getPackages();
  }

}
```

I'm really happy about any help. Also, I'd be willing to update the current android documentation for 0.57.1 when I get it working, because currently, it seems like it is based on the react-native-cli < 0.57, right? Thank you in advance!

**Comment by holparb** [comment]
Make sure you also include the proper support library for multidex support in your app/build.gradle:
`implementation "com.android.support:multidex:1.0.3"`

You also need to modify the <application> properties in the Android manifest file like this:

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.myapp">
    <application
            android:name="android.support.multidex.MultiDexApplication" >
        ...
    </application>
</manifest>

You may also need to add this part to your app level build.gradle:

`configurations.all {
    resolutionStrategy.eachDependency { DependencyResolveDetails details ->
        def requested = details.requested
        if (requested.group == 'com.android.support' && requested.name != 'multidex') {
            details.useVersion "${rootProject.ext.supportLibVersion}"
        }
    }
}`

After adding the above do a gradle clean and rebuild (you can do this from Android Studio).

Hope it helps.

**Comment by anilgurindapalli** [comment]
I have downloaded from _**npm install https://github.com/abdullah-sr/react-native-navigation#build**_ by @abdullah-sr . I have also followed suggetions of @holparb . Unfortunately I'm facing this issue. **react-native-navigation:compileReactNative57DebugJavaWithJavac**. I have benn trying number of ways but unable to solve the Issue. If it is possible can anyone Please Write a **Medium Post** on how to add **support of RN 57**. Can share the Andoid Folder which **Impleted RN 57 support**.

**Comment by RiCoTeRoX** [comment]
any chance to review this pr to merge in the next release ?

**Comment by abdullah-sr** [comment]
I'm not really sure how to get the attention of the maintainers. @guyca or whoever can approve this PR, i know you guys are busy and probably have a lot on your hands, but this PR have been open for over a month now. Please Let's try and get it merged, if it needs changes or anything let me know and I can do that too.

**Comment by ujwal-setlur** [comment]
Has happened with some of my PRs unfortunately. Looks like they have their hands full. 

I ended up migrating to react-navigation. I am quite happy with it. Migration was fairly painless as well

**Comment by vivekshah-zymr** [comment]
@nightgrey, I am facing the exact same issue as you for android. (The project runs well on iOS simulator.)

I am using,
```
"react-native-navigation": "^1.1.487"
"react-native": "0.57.1"
```

**Exception while running on Android**
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
```

**android/build.gradle**
```
android {
     compileSdkVersion 25
     buildToolsVersion "25.0.1"
     ...
 }

 dependencies {
     compile fileTree(dir: "libs", include: ["*.jar"])
     compile "com.android.support:appcompat-v7:23.0.1"
     compile "com.facebook.react:react-native:+"
     compile project(':react-native-navigation')
 }

```
And I have followed all the steps which described in [this documentation.](https://wix.github.io/react-native-navigation/#/installation-android) But still gets the error.

Even I tried to change **android/build.gradle** file with below code. But get the same error.
```
android {
    compileSdkVersion rootProject.ext.compileSdkVersion
    buildToolsVersion '28.0.2'
}
```
@holparb, I have followed your steps for my above error. But that leads to the other errors which are as below.
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
```
@abdullah-sr Please look into this issue.
Can anyone please look into this and help me out? Thank you in advance!

**Comment by RiCoTeRoX** [comment]
@vivekshah-zymr the issue reported is for V2, not for v1

**Comment by kdawgwilk** [comment]
For those using the `react-native-navigation-v1-v2-adapter` I got it to build by forcing yarn/npm to use this branch on the adapter's transitive dependency by adding the following to the `package.json`:
```js
"resolutions": {
    "react-native-navigation": "git+https://github.com/abdullah-sr/react-native-navigation.git#v2"
}
```
And changing the `missingDimensionStrategy` to use `reactNative57`

**Comment by guyca** [comment]
Hey guys, sorry for the delay

PR looks good, though it seems that RNN isn't compatible with RN 0.57. The workaround pruposed [here](https://github.com/wix/react-native-navigation/issues/2892#issuecomment-392800666) broke, I think RNN is pretty much unusable in large apps without this fix 😕

// for future guyca
```js
{
  "react": "16.5.1",
  "react-native": "0.57.1"
}
```

`exec.execSync(`node ./node_modules/react-native/local-cli/cli.js start --projectRoot ./playground/`);`

**Comment by abdullah-sr** [comment]
Thanks for merging @guyca, but what do you mean RNN isn't compatible with react-native 0.57 :D?
I've been using it with 0.57.2 and it's working for me.

**Comment by Iamsamwhoami** [comment]
@abdullah-sr RNN requires a custom synchronous UIImplementationProvider, Facebook refactored those bits for 0.57 meaning you can't pass a custom UIImplementationProvider anymore. So for large-ish apps, RNN just throws weird errors all the time :/

**Comment by abdullah-sr** [comment]
i see. well luckily I haven't run into those issues yet.

**Comment by guyca** [comment]
@Iamsamwhoami I think I have a workaround for that, hope to publish it in the net few days. Also spoke to some guys at facebook and they reintroduce the api we require.

**Comment by guyca** [comment]
Quick update, there's an internal PR at RN which reintroduces the UiImplementation api we need. If all goes well it should land in RN 0.58.
If you're extensively using react components in TopBar - I suggest you reconsider upgrading to RN 0.57.

**Comment by Dgs-asohail4** [comment]
Just tried migrating my RN 0.57 project from V1 to V2 got this error 
D:\Projects\React\React-Native Sample app\MobileApp\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:10: error: cannot find symbol
import com.facebook.react.uimanager.UIImplementationProvider;
                                   ^
  symbol:   class UIImplementationProvider
  location: package com.facebook.react.uimanager
D:\Projects\React\React-Native Sample app\MobileApp\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:23: error: cannot find symbol
    public static class Provider extends UIImplementationProvider {
                                         ^
  symbol:   class UIImplementationProvider
  location: class SyncUiImplementation
D:\Projects\React\React-Native Sample app\MobileApp\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\NavigationReactNativeHost.java:86: error: cannot find symbol
                .setUIImplementationProvider(getUIImplementationProvider())
                                             ^
  symbol:   method getUIImplementationProvider()
  location: class NavigationReactNativeHost
D:\Projects\React\React-Native Sample app\MobileApp\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:24: error: method does not override or implement a method from a supertype
        @Override
        ^
D:\Projects\React\React-Native Sample app\MobileApp\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:29: error: method does not override or implement a method from a supertype
        @Override
        ^
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
5 errors

RNN version 2.0.595

**Comment by esipavicius** [comment]
> Just tried migrating my RN 0.57 project from V1 to V2 got this error
> D:\Projects\React\React-Native Sample app\MobileApp\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:10: error: cannot find symbol
> import com.facebook.react.uimanager.UIImplementationProvider;
> ^
> symbol: class UIImplementationProvider
> location: package com.facebook.react.uimanager
> D:\Projects\React\React-Native Sample app\MobileApp\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:23: error: cannot find symbol
> public static class Provider extends UIImplementationProvider {
> ^
> symbol: class UIImplementationProvider
> location: class SyncUiImplementation
> D:\Projects\React\React-Native Sample app\MobileApp\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\NavigationReactNativeHost.java:86: error: cannot find symbol
> .setUIImplementationProvider(getUIImplementationProvider())
> ^
> symbol: method getUIImplementationProvider()
> location: class NavigationReactNativeHost
> D:\Projects\React\React-Native Sample app\MobileApp\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:24: error: method does not override or implement a method from a supertype
> @override
> ^
> D:\Projects\React\React-Native Sample app\MobileApp\node_modules\react-native-navigation\lib\android\app\src\reactNative56\java\com\reactnativenavigation\react\SyncUiImplementation.java:29: error: method does not override or implement a method from a supertype
> @override
> ^
> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> 5 errors
> 
> RNN version 2.0.595

Maybe its it: https://github.com/invertase/react-native-firebase-docs/pull/133/files
I created pull request to documentation. Please try it and write if its works. I already have working project :)

**Comment by Dgs-asohail4** [comment]
@esipavicius 

Thanks i got rid of that previous error, but now i am getting this error

> Task :app:compileDebugJavaWithJavac FAILED
D:\Projects\React\React-Native Sample app\MobileApp\android\app\src\main\java\com\sampleproject\MainApplication.java:19: error: class, interface, or enum expected
+import com.reactnativenavigation.react.NavigationReactNativeHost;
^
D:\Projects\React\React-Native Sample app\MobileApp\android\app\src\main\java\com\sampleproject\MainApplication.java:20: error: class, interface, or enum expected
+import com.reactnativenavigation.react.ReactGateway;
^
2 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 6s
83 actionable tasks: 30 executed, 53 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html

**Comment by Dgs-asohail4** [comment]
@esipavicius thanks i got it working now

**Comment by williamnvk** [comment]
```> Task :react-native-navigation:compileReactNative57WixForkReleaseJavaWithJavac FAILED```

**Comment by margaridaDinis** [comment]
I'm getting `Execution failed for task ':react-native-navigation:compileReactNative57WixForkReleaseJavaWithJavac'.
` when I run `./gradlew assembleRelease`.

It works on development builds for both Android and iOs, and release for iOs...

I have
React Native 0.57.0,
React 16.5.0 
React Native Navigation 2.1.2

**Comment by diegolmello** [comment]
@margaridaDinis It seems you need to ignore 57 Wix.
https://wix.github.io/react-native-navigation/#/docs/Installing?id=_82-ignore-other-rnn-flavors

```gradle
subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (names.contains("reactNative51") || names.contains("reactNative55") || names.contains("reactNative56") || names.contains("reactNative57WixFork")) {
                        setIgnore(true)
                    }
                }
            }
        }
    }
}
```

**Comment by margaridaDinis** [comment]
That fixed it! The build is now succeeding, thanks @diegolmello

**Comment by Haqverdi** [comment]
Hello
I have such a problem with the React version 0.57.6
error:
* What went wrong:
Execution failed for task ': app: transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

someone had a similar problem???

**Comment by hisothreed** [comment]
@Haqverdi 

solved by adding those to app/build.gradle

```
defaultConfig {
       ...
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative57_5"
       ...
}
```
dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation "com.android.support:design:${rootProject.ext.supportLibVersion}"
    implementation "com.android.support:appcompat-v7:${rootProject.ext.supportLibVersion}"
    implementation "com.android.support:support-v4:${rootProject.ext.supportLibVersion}"


    implementation "com.facebook.react:react-native:+"  // From node_modules
    implementation project(':react-native-navigation')
}
```

**Comment by NweThazin** [comment]
Hi,

Which RNN version should I update to support react native 0.57.0?
thanks

**Comment by Haqverdi** [comment]
> Hi,
> 
> Which RNN version should I update to support react native 0.57.0?
> thanks

latest works good)
