### ISSUE TITLE
Does this support react-native 0.34.1?

### ISSUE THREAD

**Issue by Jaafar-abusair** [wix/react-native-navigation#361]
### Issue Description

I have updated my react native from 0.32.1 to 0.34.1 and it stop working

:react-native-navigation:compileReleaseJavaWithJavacC:\SECO\SECOMobile\node_modules\react-native-navigation\android\app\src\main\java\com\reactnativenavigation\react\NavigationReactGateway.java:77: error: method onActivityResult in class ReactInstanceManager cannot be applied to given types;
        getReactInstanceManager().onActivityResult(requestCode, resultCode, data);
                                 ^
  required: Activity,int,int,Intent
  found: int,int,Intent
  reason: actual and formal argument lists differ in length
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
 FAILED

---
### Environment
- React Native Navigation version: 2 exp
- React Native version: 0.34.1
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): LG G3 Os 5.0

**Comment by Crash--** [comment]
Nope, not officially. 

But you can take a look here : https://github.com/wix/react-native-navigation/pull/357 ;)

**Comment by brunolemos** [comment]
@guyca @DanielZlotin is there a checklist of the missing changes to it support the latest rn version? Maybe the community could help.

**Comment by beast** [comment]
Second with @brunolemos . I submitted the PR mentioned earlier. Actually we used RN Navigation heavily and we actually did a lot of hacks in order to keep up with newer versions of React Native or add our own functionalities. If WIX @guyca @DanielZlotin  could label the issues or a checklist, it will be much easier for the community to help. You probably need one to track your own investigations for upgrades anyway? Thanks again for the great package and I just hope we could help more.

**Comment by DanielZlotin** [comment]
That's a good idea. Thanks

**Comment by rawrmaan** [comment]
I would also love to help the project stay up-to-date if there are tasks available.

**Comment by srimajji** [comment]
I think this might be an android issue? It is working on ios with `react-native@0.35`

**Comment by alexcurtis** [comment]
Getting strange issues with 0.35 - When I resetTo and try and push, I get this:

Error: You attempted to set the key `onPress` with the value `"screenInstanceID5_events"` on an object that is meant to be immutable and has been frozen. at Error (native) at throwOnImmutableMutation

```
Error: You attempted to set the key `onPress` with the value `"screenInstanceID5_events"` on an object that is meant to be immutable and has been frozen.
    at Error (native)
    at throwOnImmutableMutation (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:13935:7)
    at _mergeScreenSpecificSettings (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:84750:40)
    at Object.navigatorPush [as push] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:84771:1)
    at Navigator.push (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:102572:27)
    at login$ (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:121266:2432)
    at tryCatch (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:29140:29)
    at GeneratorFunctionPrototype.invoke [as _invoke] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:29414:12)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:29173:13)
    at next (http://localhost:8081/index.ios.bundle?platform=ios&dev=true&minify=false&hot=true:118787:17)"
```

**Comment by t2n3qqq** [comment]
I have same error trying to open modal that was previously closed, and after I trying to push screen, than pop back and push that screen again. Using react-native: 0.35.0-rc.0.
@alexcurtis Did you solve this problem?

**Comment by alexcurtis** [comment]
@t2n3qqq Nope. I downgraded to 0.32.1 and now waiting patiently for support on 0.35. :-)

**Comment by Jaafar-abusair** [comment]
Guys can you add this [357](https://github.com/wix/react-native-navigation/pull/357), It's really easy and straight forward, I don't want to use an external version of the code?

**Comment by lakhman** [comment]
Not sure if this is related, but I get the following error on android:

```
/Users/user/xCode/LayoutTest/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java:77: error: method onActivityResult in class ReactInstanceManager cannot be applied to given types;
        getReactInstanceManager().onActivityResult(requestCode, resultCode, data);
                                 ^
  required: Activity,int,int,Intent
  found: int,int,Intent
  reason: actual and formal argument lists differ in length
/Users/user/xCode/LayoutTest/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/views/collapsingToolbar/CollapsingTextView.java:54: error: package android.support.v7.appcompat.R does not exist
                android.support.v7.appcompat.R.styleable.Toolbar, android.support.v7.appcompat.R.attr.toolbarStyle, 0);
                                              ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

Hopefully it's just an issue with the update to 0.3x+, I'll try again tomorrow. - I understand a new version is coming very soon! - Patiently waiting!..

**Comment by guyca** [comment]
@lakhman Not related, but thanks for reporting 👍 
Should be fixed by 8c923b2818f171fdeda66353d3fd8ffba374e6bb

**Comment by DanielZlotin** [comment]
works in `^2.0.0-experimental.141`
