### ISSUE TITLE
Cannot find symbol ReactActivity

### ISSUE THREAD

**Issue by ChiroV3** [wix/react-native-navigation#7511]
## 🐛 Bug Report

After creating react native project and installing react-native-navigation project doesn't build on android

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)?

Yes

## To Reproduce

1. npx react-native init
2. yarn add react-native-navigation
3. npx rnn-link
4. fix index.js
5. react-native run-android

## Expected behavior

App builds

## Actual Behavior

Error is shown:

MainActivity.java:21: error: cannot find symbol
    public MainActivityDelegate(ReactActivity activity, String mainComponentName) 

symbol:   class ReactActivity
  location: class MainActivityDelegate

## Your Environment

- React Native Navigation version: 7.27.1
- React Native version: 0.68.1
- Platform(s) (iOS, Android, or both?): Android
- Device info (Simulator/Device? OS version? Debug/Release?): Simulator

**Comment by bfricka** [comment]
Since this package doesn't currently support the new architecture, you'll need to make sure it's disabled and your `MainActivity.java` should be essentially empty:

```java
import com.reactnativenavigation.NavigationActivity;

public class MainActivity extends NavigationActivity {
}
```
This should allow it to work on RN 0.68.

That said, I haven't seen a concrete confirmation that the new stuff will be supported by this project, and if it's not, it's unfortunately a basically dead project anyways.

**Comment by phuongwd** [comment]
Strange, this pull request is related to RN v0.68 https://github.com/wix/react-native-navigation/pull/7500

**Comment by Irenedan** [comment]
@bfricka Hi guy, this is what I used: "react-native-navigation": "7.27.1", so what's the newest version I can use of 'react-native', probably 0.66.3? What version is their best partner?
I always get the error: react-native-navigation:compileReactNative66DebugKotlin

**Comment by theahmedsabbir** [comment]
having this issue too.. will there be any update from wix developers?

**Comment by eightyfive** [comment]
@bfricka what do you mean "new architecture" and where did you read (or not read...) that they won't support "it"?

It's very concerning.

Maybe @guyca can step in and let us know if it's FUD or if we can count on that lib going forward.

**Comment by eightyfive** [comment]
By the way I could fix the error simply by importing `ReactActivity` in `MainActivity.java`:

```java
package com.yourorg.YourAppName;

import com.facebook.react.ReactActivity;

// ...
```

**Comment by yedidyak** [comment]
Closing this as part of a maintainer cleanup of open issues older than one year.

Decision: Closed: old setup/compatibility report without evidence it is critical on latest RNN.

If this still reproduces on the latest React Native Navigation with a minimal reproduction, please open a new issue with current RN/RNN versions and repro steps.
