### PR TITLE
Work in react-native 0.41

### PR DESCRIPTION
**Pull request by carlosroberto555**
It's working in react-native 0.41 (Android and iOS)
I didn't have any problems

### CODE REVIEW

**Comment by messense** [comment]
FYI, please consider use `__has_include()` discussed in

https://github.com/Microsoft/react-native-code-push/pull/670#discussion_r96869599

**Comment by simonmitchell** [comment]
@MetinSeylan @messense for your information, the `__has_include()` should be this way around: 
`
#if __has_include(<React/RCTRedBox.h>)
#import <React/RCTRedBox.h>
#elif __has_include("RCTRedBox.h")
#import "RCTRedBox.h"
#elif __has_include("React/RCTRedBox.h")
#import "React/RCTRedBox.h"   // Required when used as a Pod in a Swift project
#endif
`
as the compiler does have access to the direct import of `#import "RCTRedBox"` in RN 0.40.0, but it just causes compiler errors :)

**Comment by tonyrewin** [comment]
`
:app:compileDebugJavaWithJavac
/myapp/android/app/src/main/java/com/myapp/MainApplication.java:8: error: cannot find symbol
import com.reactnativenavigation.NavigationReactPackage;
                                ^
  symbol:   class NavigationReactPackage
  location: package com.reactnativenavigation
/myapp/android/app/src/main/java/com/myapp/MainApplication.java:33: error: cannot find symbol
            new NavigationReactPackage(),
                ^
  symbol: class NavigationReactPackage
2 errors
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
`

**Comment by carlosroberto555** [comment]
Did you follow the gradle steps?
[https://github.com/wix/react-native-navigation/wiki/Installation---Android](Android configuration)

**Comment by MetinSeylan** [comment]
merge?

**Comment by carlosroberto555** [comment]
@ryanbrozo had found an error,
But I think it's fixed in the last merge

**Comment by ryancoughlin** [comment]
Nice!

**Comment by guyca** [comment]
Support for RN 0.41.2 was added in 503eef5 cc94e02 fc357ba
Thanks a lot @carlosroberto555
