### ISSUE TITLE
[V2][Android] Can't create release error : cannot find symbol optionsPresenter.applyOrientation

### ISSUE THREAD

**Issue by sbayd** [wix/react-native-navigation#3396]
### Issue Description

While trying to run the application in release mode with `react-native run-android --variant=release` command, the following error is occurring. 

I am using latest react, react-native and react-native-navigation versions.  It is working with react-native-navigation@2.0.2301

```
> Task :react-native-navigation:compileReactNative55ReleaseJavaWithJavac FAILED
mobile/node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/views/StackLayout.java:37: error: cannot find symbol
        optionsPresenter.applyOrientation(options.orientationOptions);
```

### Steps to Reproduce / Code Snippets / Screenshots

Use the related versions below and try to run the application in release mode on Android.

![screen shot 2018-06-20 at 4 34 08 pm](https://user-images.githubusercontent.com/6469914/41661683-ed6afeb6-74a7-11e8-8802-5541631cb819.png)
---
### Environment
* React Native Navigation version: 2.0.2364
* React Native version: 0.56.0-rc2
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Device & Simulator Release

**Comment by nSimonFR** [comment]
Upgrading to latest version `2.0.2398` seems to have fixed this for me.
@sbayd Do you still have issues after upgrading ?

**Comment by sbayd** [comment]
Hey Simon,

It looks fixed with the latest navigation and stable react-native@0.56

Thanks!
