### ISSUE TITLE
nativeCommandsModule.getLaunchArgs undefined

### ISSUE THREAD

**Issue by Jonahss** [wix/react-native-navigation#4722]
### Issue Description

Calling the following:
```js
Navigation.getLaunchArgs()
```

Results in error:
```
undefined is not a function (evaluating 'this.nativeCommandsModule.getLaunchArgs(commandId)')
```

Has anyone confirmed that this works in RNN v2.7.1?

---
### Environment
* React Native Navigation version: 2.7.1
* React Native version: 0.57.8
* Platform(s) (iOS, Android, or both?): Android (haven't tested iOS)
* Device info (Simulator/Device? OS version? Debug/Release?): Emulator, API v28

**Comment by retyui** [comment]
> * (haven't tested iOS)

It's work fine on IOS

**Comment by ioannisGiak89** [comment]
@Jonahss did you get this working at all?

**Comment by Jonahss** [comment]
This was over a year ago, so the details are a little fuzzy. I looked at the repo I was trying to use this in and I think I did not succeed in getting it working.
My first suggestion would be to update absolutely everything to the latest version (which can be a huge pain).
