### ISSUE TITLE
Debug Issue:  Execution failed for task ':react-native-navigation:compileReactNative60DebugKotlin' 

### ISSUE THREAD

**Issue by vykumar** [wix/react-native-navigation#7632]
## 🐛 Bug Report

It was working fine when I was compiling with RNN v6.0.1 & RN v0.61.5, suddenly It start giving below error on compilation:
Execution failed for task ':react-native-navigation:compileReactNative60DebugKotlin'

I tried to resolve by upgrading the RNN version 7.0.0, but still same error.

Thanks!

### Have you read the [Contributing Guidelines on issues](https://wix.github.io/react-native-navigation/docs/meta-contributing/)? 

Yeah I have seen the possible solution but nothing is appropriate.

## To Reproduce

(Write your steps here:)

1.  run the command react-native run-android

## Expected behavior

App start

(Write what you thought would happen.)

## Actual Behavior

Execution failed for task ':react-native-navigation:compileReactNative60DebugKotlin'

(Write what happened. Add screenshots, if applicable.)

## Your Environment

React Native Navigation version: 6.0.1
React Native version: 0.61.5
Platform(s) (iOS, Android, or both?): Android
Device info (Simulator/Device? OS version? Debug/Release?): Both, Android 7-10

## Reproducible Demo

N/A

### Are you willing to resolve this issue by submitting a Pull Request?

 - ✖️ &nbsp; Yes, I have the time, and I know how to start.
 - ✖️  &nbsp; Yes, I have the time, but I don't know how to start. I would need guidance.
 -  ✅ &nbsp; No, I don’t have the time and I’m okay to wait for the community / maintainers to resolve this issue.

**Comment by erkutr-prog** [comment]
I have the same error in RN 0.66.5.It happened after I bumped the RN version to 0.66.5.I thought there was something wrong with the JDK version but I've tried different versions but it didn't work.Anyone else getting this error?
<img width="1622" alt="Screen Shot 2022-11-08 at 10 27 49" src="https://user-images.githubusercontent.com/65131924/200501028-564bf83e-678e-4613-a006-e6d071d763d1.png">

**Comment by jwh-hutchison** [comment]
I'm getting the same issue after having updated to RN 0.66.5. My error stack is about 100 errors of `...error: cannot find symbol` and `...error: package <some package> does not exist`. I haven't really found many other threads discussing this.

**Comment by tukaAlalami** [comment]
i have the same error Execution failed for task ':react-native-navigation:compileReactNative63DebugKotlin'.
after i upgrade from react native .0.67.2 to 0.67.5
any help ?

**Comment by yogevbd** [comment]
Can you please test it with `7.30.1-snapshot.745`?

**Comment by abhishek-malaviya** [comment]
I was having the same issue with the latest version 7.30.1. I have downgraded this to **7.27.1** and now it builds successfully.

**Comment by yogevbd** [comment]
Solved in version 7.30.2

**Comment by nathantqn** [comment]
Hi @yogevbd @vykumar, I'm also using RN v0.61.5 and suddenly got this issue, I already upgraded the RNN into the latest version but the error still remains, could you please help me to understand how to resolve this
