### ISSUE TITLE
Could not compile Android for RN 0.63 and RNN 7.x / 6.x

### ISSUE THREAD

**Issue by j0nd0n7** [wix/react-native-navigation#6623]
### Issue Description

Could not compile android from a fresh RN and RNN install and following [install instructions](https://wix.github.io/react-native-navigation/docs/installing)
Versions:

### Steps to Reproduce / Code Snippets / Screenshots

yarn run v1.12.3
$ cd ./android && ./gradlew app:assembleDebug && ./gradlew installDebug

> Task :react-native-navigation:compileReactNative63DebugJavaWithJavac FAILED
/a/path//node_modules/react-native-navigation/lib/android/app/src/main/java/com/reactnativenavigation/viewcontrollers/stack/StackPresenter.java:317: error: incompatible types: cannot infer type-variable(s) T#1,T#2,S
            result.add(take(first(perform(currentButtons, null, Map::values), button -> button.getButton().equals(b)), createButtonController(b)));
                           ^
    (argument mismatch; S cannot be converted to Collection<ButtonController>)
  where T#1,T#2,S are type-variables:
    T#1 extends Object declared in method <T#1>first(Collection<T#1>,Filter<T#1>)
    T#2 extends Object declared in method <T#2,S>perform(T#2,S,FuncR1<T#2,S>)
    S extends Object declared in method <T#2,S>perform(T#2,S,FuncR1<T#2,S>)
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileReactNative63DebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 10s
13 actionable tasks: 2 executed, 11 up-to-date
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[FILL THIS OUT]

### Environment
* React Native Navigation version: 0.63.3
* React Native version: 7.1.0, 7.0.0, 6.12.0, 6.11.0
* Platform: Android
* Device info (Simulator/Device? OS version? Debug/Release?): Debug - no device reached

``

**Comment by guyca** [comment]
@j0nd0n7 Which java version are you using? What's the output of `javac -version` ?
This seems like an issue with your local environment. Perhaps you need to install/update JDK: `brew cask install adoptopenjdk/openjdk/adoptopenjdk8`

**Comment by j0nd0n7** [comment]
@guyca My JAVA version is 1.8.0_25
I already have my project working with RNN 6.3.1 and RN 0.61.5 with no issues. I tried to upgrade and it didn't compiled, then I tried with a fresh RN install and adding only the RNN and it doens't compile resulting in the output pasted.

Have you tried to installing RNN 7.x to RN 0.63.3 following the instructions?

**Comment by shankarGdev** [comment]
Adding `multiDexEnabled true` in `android/app/build.gradle` fix issue for me

```
defaultConfig {
    ......
    ......
   
    multiDexEnabled true 
}
```

**Comment by JimTeva** [comment]
Had the same issue with RNN 7.16.0, RN 0.64.2, Java 1.8.0. (very old yes)
@guyca was right, Java version was outdated and I updated it to 11 LTS, then it worked!

**Comment by JimTeva** [comment]
@j0nd0n7 I think @guyca is right, updating JDK is important
```
brew cask install adoptopenjdk/openjdk/adoptopenjdk8
```
or
```
brew cask install adoptopenjdk/openjdk/adoptopenjdk11
```

also:

1. in _./android/app/build.gradle_

```
defaultConfig {
        applicationId "com.newlinecode.mobie"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        missingDimensionStrategy "RNN.reactNativeVersion", "reactNative63" // <---

        ...
    }
```

2. in _./android/build.gradle_ at the end of the file, make sure to remove all react-native variants that you don't use

```

subprojects { subproject ->
    afterEvaluate {
        if ((subproject.plugins.hasPlugin('android') || subproject.plugins.hasPlugin('android-library'))) {
            android {
                variantFilter { variant ->
                    def names = variant.flavors*.name
                    if (names.contains("reactNative51") || names.contains("reactNative55") || names.contains("reactNative56") || names.contains("reactNative57") || names.contains("reactNative57_5") || names.contains("reactNative60") || names.contains("reactNative62")) {
                        setIgnore(true)
                    }
                }
            }
        }
    }
}
```
