### ISSUE TITLE
Official Android API compatibility?

### ISSUE THREAD

**Issue by mobitar** [wix/react-native-navigation#1998]
RNN works great with Android 5.0+. But I just tried testing on 4.4 for the first time, and the app immediately crashes on launch:

```
java.lang.NoClassDefFoundError: com.reactnativenavigation.react.NavigationReactGateway$ReactNativeHostImpl
    at com.reactnativenavigation.react.NavigationReactGateway.<init>(NavigationReactGateway.java:31)
```

It seems a few others have experienced the same:
https://github.com/wix/react-native-navigation/issues/1805
https://github.com/wix/react-native-navigation/issues/1449#issuecomment-333305274

Is there any official guidance on the minimum supported Android version for RNN?

**Comment by freiserg** [comment]
@mobitar Do you use code-push?

**Comment by mobitar** [comment]
No I don't.

**Comment by freiserg** [comment]
I had so problem when I tried to used code-push. RNN works on android 4.x.

**Comment by swapnil001** [comment]
Hi,

Any solution for this?

**Comment by guyca** [comment]
Closing for now as @freiserg indicates RNN works on 4.4.
We've stopped supporting Android 4.4, so we actually don't develop for it in mind anymore.

**Comment by varungupta85** [comment]
Do you use multi-dex?

**Comment by perrosnk** [comment]
@varungupta85 I do use multi-dex. What's the problem about it? Have you found a solution?

**Comment by varungupta85** [comment]
@perrosnk if you use multi-dex, then you will need to enable multi-dex in the `MainApplication.java` for lower OS versions. Try adding below to `MainApplication.java`

```java
@Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }
```
