### ISSUE TITLE
[v2] [Android] How should I config custom splash screens?

### ISSUE THREAD

**Issue by gabrielvcbessa** [wix/react-native-navigation#3389]
I want a simple white splash screen with my app logo centralized. I was easy to do on iOS, because you just need to make some changes on XCode, but how can I do it on Android? Should I change my NavigationApplication?

---
### Environment
* React Native Navigation version: 0.55.1
* React Native version: 2.0.2275
* Platform(s) (iOS, Android, or both?): FILL THIS OUT
* Device info (Simulator/Device? OS version? Debug/Release?): FILL THIS OUT

**Comment by ilovett** [comment]
I'd like to see it work with a splash activity like in this article:

https://medium.com/handlebar-labs/how-to-add-a-splash-screen-to-a-react-native-app-ios-and-android-30a3cec835ae

```
        <activity
            android:name=".SplashActivity"
            android:theme="@style/SplashTheme"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <activity
          android:name=".MainActivity"
          android:label="@string/app_name"
          android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
          android:windowSoftInputMode="adjustResize"
          android:exported="true"
        />
```

Loading the app shows the splash screen above until the first root is set / changed for the first time...

**Comment by cihancil** [comment]
v1 had a function called **createSplashLayout** which worked great for me.

I couldn't find an equivalent of that for v2.

**NavigationActivity** class needs similar function. In case if I try to set my own contentview, NavigationActivity overrides this with this line of code. 

```
setContentView(navigator.getView());
```

**Comment by ilovett** [comment]
While it's nice to get Splash integration "for free" with react native navigation, the resulting android splash screen in v1 had a short moment of white screen when launching. The SplashActivity will show the splash screen immediately without any white screen.

**Comment by gabrielvcbessa** [comment]
@ilovett Do you have an example using SplashActivity and RNN?

**Comment by GuillotJessica** [comment]
@gabrielvcbessa did you figured this out on rnn v2, btw you mixed up rn version and rnn version

**Comment by jinshin1013** [comment]
@guyca Is there an equivalent api for creating or getting the splash screen like we did on V1? On [V1](https://wix.github.io/react-native-navigation/#/android-specific-use-cases?id=splash-screen). On V2, documentation is missing about controlling splash screen. On V2 Playground [playground](https://github.com/wix/react-native-navigation/blob/v2/playground/android/app/src/main/java/com/reactnativenavigation/playground/MainApplication.java#L19) it seems like on MainApplcation.java file, it calls FragmentCreator?

**Comment by phuongwd** [comment]
@jinshin1013 

react-native-navigation@2.0.2465 https://github.com/wix/react-native-navigation/commit/4adc1485a3cb939e5ab173bf438e25719f5a2dac

**Comment by sytolk** [comment]
Thanks @phuongwd it works!

**Comment by FeniXenAaaa** [comment]
Guys, does some have any guide on how to implement splash screen with RNN v2? I tried to use this [plugin ](https://github.com/crazycodeboy/react-native-splash-screen) and my splash is shown but looks like something crashes inside so I don't have ability to hide it (even JS debugger doesn't start).

I can't see splashscreen example in v2 playground project (and I could launch it locally).
How to setup splashscreen in RNN v2?

**Comment by guyca** [comment]
You can override `onCreate` in your `MainActivity` and set the splash screen using `setContentView`

```java
public class MainActivity extends NavigationActivity {
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.splash);
    }
}
```

**Comment by ammichael** [comment]
If anyone is still having this issue after migrating from v1, this worked for me: 

```
public class MainActivity extends NavigationActivity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(this.createSplashLayout());
  }

  public LinearLayout createSplashLayout() {
    LinearLayout splash = new LinearLayout(this);
    Drawable launch_screen_bitmap = ContextCompat.getDrawable(getApplicationContext(), R.drawable.launch_screen);
    splash.setBackground(launch_screen_bitmap);

    return splash;
  }
}
```

**Comment by rendomnet** [comment]
@guyca >  FAILED
Task :app:compileDebugJavaWithJavac FAILED
**/android/app/src/main/java/com/dailyhero/MainActivity.java:12: error: cannot find symbol
    protected void onCreate(@Nullable Bundle savedInstanceState) {
                                      ^
  symbol:   class Bundle
  location: class MainActivity
**/android/app/src/main/java/com/dailyhero/MainActivity.java:12: error: cannot find symbol
    protected void onCreate(@Nullable Bundle savedInstanceState) {

**Comment by Johncy1997** [comment]
Someone tell me, how to change the splash screen layout based on my i18n.locale.

**Comment by evaldsurtans** [comment]
Right now there is an overridable function for this purpose:

```
public class MainActivity extends NavigationActivity {

    @Override
    protected void addDefaultSplashLayout() {
        LinearLayout splash = new LinearLayout(this);
        Drawable splash_background = ContextCompat.getDrawable(getApplicationContext(), R.drawable.splash_background);
        splash.setBackground(splash_background);
        setContentView(splash);
        SystemClock.sleep(1000 * 5);
    }

}
```


res/drawable/splash_background.xml
```
<?xml version="1.0" encoding="utf-8"?>
<layer-list xmlns:tools="http://schemas.android.com/tools"
    xmlns:android="http://schemas.android.com/apk/res/android">

    <item android:drawable="@android:color/white" />

    <item
        android:width="170dp"
        android:height="122dp"
        android:gravity="center"
        android:drawable="@drawable/src_resources_branding"
        />

</layer-list>
```

**Comment by juddey** [comment]
Just to add to add to @evaldsurtans solution, the following imports are required in `mainactivity`:

```
import android.graphics.drawable.Drawable;
import android.support.v4.content.ContextCompat;
import android.widget.LinearLayout;
````

**Comment by richardbumm** [comment]
@evaldsurtans All I get is this error:

AAPT: error: resource drawable/background_splash (aka com.bc:drawable/background_splash) not found.

**Comment by Asim13se** [comment]
@juddey For RN 0.60+ these are the new imports:
```
import android.graphics.drawable.Drawable;
import androidx.core.content.ContextCompat;
import android.widget.LinearLayout;
```
