### ISSUE TITLE
Android example does not work with RN 0.25

### ISSUE THREAD

**Issue by webzepter** [wix/react-native-navigation#31]
I try to run `example-redux` example on Android using latest RN (0.25.1). But an error occurs during start:
```
java.lang.NoSuchMethodError: No virtual method onResume(Landroid/app/Activity;Lcom/facebook/react/modules/core/DefaultHardwareBackBtnHandler;)V in class Lcom/facebook/react/ReactInstanceManager; or its super classes (declaration of 'com.facebook.react.ReactInstanceManager' appears in /data/app/com.exampleredux-2/base.apk)
    at com.reactnativenavigation.activities.BaseReactActivity.onResume(BaseReactActivity.java:187)
    at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1258)
    at android.app.Activity.performResume(Activity.java:6312)
    at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3092)
    at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3134)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2481)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
Using RN 0.21 application starts without crash.

**Comment by guyca** [comment]
@webzepter thanks for reporting this. Will publish a version supporting RN 0.25 on Thursday or Sunday next week.

**Comment by alexeypodolian** [comment]
Also have the same issue.

**Comment by guyca** [comment]
Fixed in version 1.0.1.
