### PR TITLE
Fix Android compilation errors.

### PR DESCRIPTION
**Pull request by Mayzie**
As it is, trying to compile the current package will produce the
following compilation errors:

```
error: cannot find symbol class MeasureSpecProvider
error: cannot find symbol class SizeMonitoringFrameLayout
```

This is due to these two classes not existing in the *.uimanager
package, but rather the *.uimanager.common package.

See the directory structure at: https://github.com/facebook/react-native/tree/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/common

This commit corrects the above mistake introduced in commit 4c8d48b

### CODE REVIEW

**Comment by guyca** [comment]
This will be fixed by #3317 in a backwards compatible manner, hopefully this week.
