### ISSUE TITLE
Error with react native navigation on new react-native-0.57.0

### ISSUE THREAD

**Issue by lule23** [wix/react-native-navigation#3996]
### Issue Description

I installed new react native 0.57 and when i run npm run android a got too much errors.

### Steps to Reproduce / Code Snippets / Screenshots

This are the errors:

```
> Task :react-native-navigation:compileDebugJavaWithJavac FAILED
/home/luka/Projects/nasa-peceranja-native/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java:13: error: cannot find symbol
import com.facebook.react.uimanager.UIImplementationProvider;
                                   ^
  symbol:   class UIImplementationProvider
  location: package com.facebook.react.uimanager
/home/luka/Projects/nasa-peceranja-native/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java:35: error: cannot find symbol
        public NavigationReactGateway(final UIImplementationProvider customImplProvider) {
                                            ^
  symbol:   class UIImplementationProvider
  location: class NavigationReactGateway
/home/luka/Projects/nasa-peceranja-native/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java:15: error: cannot find symbol
import com.facebook.react.uimanager.UIImplementationProvider;
                                   ^
  symbol:   class UIImplementationProvider
  location: package com.facebook.react.uimanager
/home/luka/Projects/nasa-peceranja-native/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/NavigationApplication.java:58: error: cannot find symbol
    protected UIImplementationProvider getUIImplementationProvider() {
              ^
  symbol:   class UIImplementationProvider
  location: class NavigationApplication
/home/luka/Projects/nasa-peceranja-native/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java:45: error: cannot find symbol
                                protected UIImplementationProvider getUIImplementationProvider() {
                                          ^
  symbol: class UIImplementationProvider
/home/luka/Projects/nasa-peceranja-native/node_modules/react-native-navigation/android/app/src/main/java/com/reactnativenavigation/react/NavigationReactGateway.java:44: error: method does not override or implement a method from a supertype
                                @Override
                                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
6 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-navigation:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details
```

---
### Environment
* React Native Navigation version: 1.1.476
* React Native version: 0.57.0
* Platform(s) (iOS, Android, or both?): Android
* Device info (Simulator/Device? OS version? Debug/Release?): Nexus 5X

**Comment by epileftro85** [comment]
have you figure this out? i have the same problem

**Comment by lule23** [comment]
Yes i did. U need to install latest version of react native navigation so its compatibile with react native 0.57. But after that there is new error about sdk. Its only for me like that, so i downgraded react native. U can try and tell us what happened.

**Comment by makirby** [comment]
There is a PR for 0.57.0 support here https://github.com/wix/react-native-navigation/pull/3851

**Comment by Krishna-Vamsi-Chintalapati** [comment]
At present react-native-navigation only works with react-native versions 0.51, 0.55 and 0.56. So downgrade your react-native to lower versions and the project will work fine.

**Comment by LRNZ09** [comment]
[Related issue here](https://github.com/wix/react-native-navigation/issues/3831)

**Comment by Dgs-asohail4** [comment]
Any update on this?

**Comment by anhtuank7c** [comment]
Any new?
