### ISSUE TITLE
Example not working on iOS simulator

### ISSUE THREAD

**Issue by ivanakimov** [wix/react-native-navigation#177]
```
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

Am I missing something? Simply cloned the repo and did `react-native run-ios` after `npm install`.

**Comment by chrise86** [comment]
I'm getting the following when running in the simulator:

```
this._nativeModule.addListener is not a function. (In 'this._nativeModule.addListener(eventType)', 'this._nativeModule.addListener' is undefined)
```

**Comment by swhamilton** [comment]
@ivanakimov @chrise86 What environments were you guys running? (iOS vs Android, RN version, react-native-navigation version)?

I had the `this._nativeModule.addListener is not a function. (In 'this._nativeModule.addListener(eventType)', 'this._nativeModule.addListener' is undefined)
` issue for iOS simulator. Usually means something went wrong with compiling. To fix it I simply close the simulator, close the React Native packager window, then `react-native run-ios`. 

Sometimes the simulator crashes before your packager has loaded completely. Try refreshing the app in the simulator once your packager reads something like this: 
```
transformed 595/595 (100%)
[2:53:58 PM] <END>   find dependencies (11905ms)
[2:54:02 PM] <END>   request:/index.ios.bundle?platform=ios&dev=true (15745ms)
```
Hope that helps.

BTW, it's currently working for me with RN v0.30 on iOS.

**Comment by ivanakimov** [comment]
@swhamilton RN 0.30 / Mac OS X 10.11.5 / iPhone 6 / iOS 9.3 / react-native-navigation@1.0.30

**Comment by swhamilton** [comment]
@ivanakimov I am not sure if react-native-navigation@1.0.30 will work with RN 0.30. From the v2.0 branch docs it says "Make sure you are using react-native version >= 0.25.1". 

Try to use the simple example app (non-redux) from the repo with the following dependencies:
```
{
  "name": "NavigationTest",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "react": "15.2.1",
    "react-native": "0.30.0",
    "react-native-navigation": "^2.0.0-experimental.65"
  }
}
```

Also, I started a fresh react-native init with version 0.30 and added react-native-navigation using the installation steps provided in the readme.md. let me know if you still have issues after using these package versions with a fresh app.

**Comment by ivanakimov** [comment]
Thanks for the follow up @swhamilton. Just now tried to follow instructions to run a [non-redux example](https://github.com/wix/react-native-navigation/tree/master/example) from a fresh install, and got other errors.

TBH, I've implemented needed functionality using other modules, so I'll let someone else take over this issue (or let me know if you want me to close).

**Comment by swhamilton** [comment]
Thanks for trying out the steps, sorry it didn't get you any further. I'll leave it open a few more days before closing. Anyone else can chime in here if they want to try out the steps.

**Comment by DanielZlotin** [comment]
Please see #234
